version: '3.8'

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
    depends_on:
      - redis
